#!/bin/bash

# Simple munin-node module to read the temperature from
# a sensor connected by i2c
#
# (c) Marco Tedaldi <tedaldi@hifo.uzh.ch>
# License: MIT, http://opensource.org/licenses/MIT

case $1 in
    config)
        cat <<'EOM'
graph_title Fan Speed
graph_vlabel speed
speed.label rpm
graph_category ambient
speed.warning 1440
speed.critical 1550
EOM
	exit 0;;
esac
printf "speed.value "
cat /run/lock/dacval
printf "\n"

