#!/bin/bash

# Simple munin-node module to read the temperature from
# a sensor connected by i2c
#
# (c) Marco Tedaldi <tedaldi@hifo.uzh.ch>
# License: MIT, http://opensource.org/licenses/MIT

case $1 in
    config)
        cat <<'EOM'
graph_title Temperature Sensor
graph_vlabel temperature
temperature.label temperature
graph_category ambient
temperature.warning 25
temperature.critical 28
EOM
	exit 0;;
esac
printf "temperature.value "
python /usr/share/munin/plugins/temperature.py

